-- Retail Sales Order Management - OLTP Schema
-- Target database: PostgreSQL 12+
-- Model: normalized transactional schema based on the final ER diagram.

-- DROP SCHEMA IF EXISTS retail_sales CASCADE;

CREATE SCHEMA IF NOT EXISTS retail_sales;
SET search_path TO retail_sales;

-- ============================================================
-- 1. Master data tables
-- ============================================================

CREATE TABLE IF NOT EXISTS customers (
    customer_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR(100) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    phone_number    VARCHAR(30),
    date_joined     DATE NOT NULL DEFAULT CURRENT_DATE,

    CONSTRAINT uq_customers_email UNIQUE (email),
    CONSTRAINT ck_customers_email_format
        CHECK (email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$')
);

COMMENT ON TABLE customers IS 'Customer master table. One row represents one customer who can place orders.';
COMMENT ON COLUMN customers.customer_id IS 'Surrogate primary key for a customer.';
COMMENT ON COLUMN customers.email IS 'Customer email. Enforced as unique because it is commonly used for customer identification.';

CREATE TABLE IF NOT EXISTS store_branch (
    store_branch_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_branch_name      VARCHAR(150) NOT NULL,
    store_branch_location  VARCHAR(255) NOT NULL,

    CONSTRAINT uq_store_branch_name UNIQUE (store_branch_name)
);

COMMENT ON TABLE store_branch IS 'Store branch master table. A branch can process many customer orders.';

CREATE TABLE IF NOT EXISTS products (
    product_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name    VARCHAR(200) NOT NULL,
    category_id     BIGINT NOT NULL,
    price           NUMERIC(12, 2) NOT NULL,
    stock_qty       INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT ck_products_price_nonnegative CHECK (price >= 0),
    CONSTRAINT ck_products_stock_qty_nonnegative CHECK (stock_qty >= 0),
    CONSTRAINT uq_products_name_category UNIQUE (product_name, category_id)
);

COMMENT ON TABLE products IS 'Product catalog table containing items available for sale.';
COMMENT ON COLUMN products.category_id IS 'Product category identifier retained from requirements. Category detail can be normalized into a product_category table in a future enhancement.';

-- ============================================================
-- 2. Transaction header table
-- ============================================================

CREATE TABLE IF NOT EXISTS orders (
    order_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id      BIGINT NOT NULL,
    order_date       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_amount     NUMERIC(12, 2) NOT NULL DEFAULT 0,
    store_branch_id  BIGINT NOT NULL,

    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers (customer_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_orders_store_branch
        FOREIGN KEY (store_branch_id)
        REFERENCES store_branch (store_branch_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT ck_orders_total_amount_nonnegative CHECK (total_amount >= 0)
);

COMMENT ON TABLE orders IS 'Order header table. Each order belongs to one customer and is processed by one store branch.';
COMMENT ON COLUMN orders.total_amount IS 'Order-level total amount. This should equal the sum of related order_items.line_amount after discounts/taxes as defined by business rules.';

-- ============================================================
-- 3. Transaction detail table
-- ============================================================

CREATE TABLE IF NOT EXISTS order_items (
    order_item_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT NOT NULL,
    product_id     BIGINT NOT NULL,
    qty            INTEGER NOT NULL,
    line_amount    NUMERIC(12, 2) NOT NULL,

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders (order_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id)
        REFERENCES products (product_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT ck_order_items_qty_positive CHECK (qty > 0),
    CONSTRAINT ck_order_items_line_amount_nonnegative CHECK (line_amount >= 0),
    CONSTRAINT uq_order_items_order_product UNIQUE (order_id, product_id)
);

COMMENT ON TABLE order_items IS 'Line item table resolving the many-to-many relationship between orders and products.';
COMMENT ON COLUMN order_items.line_amount IS 'Sales amount for the order line. The value can be calculated from quantity, sale price, discounts, and taxes by application or ETL logic.';

-- ============================================================
-- 4. Order supporting transaction tables
-- ============================================================

CREATE TABLE IF NOT EXISTS payments (
    payment_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id                BIGINT NOT NULL,
    payment_method          VARCHAR(50) NOT NULL,
    payment_amount          NUMERIC(12, 2) NOT NULL,
    payment_status          VARCHAR(30) NOT NULL,
    transaction_timestamp   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payments_order
        FOREIGN KEY (order_id)
        REFERENCES orders (order_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT ck_payments_amount_nonnegative CHECK (payment_amount >= 0),
    CONSTRAINT ck_payments_method
        CHECK (payment_method IN ('Cash', 'Credit Card', 'Debit Card', 'Bank Transfer', 'Wallet', 'Gift Card', 'Other')),
    CONSTRAINT ck_payments_status
        CHECK (payment_status IN ('Pending', 'Completed', 'Failed', 'Refunded', 'Cancelled'))
);

COMMENT ON TABLE payments IS 'Payment records for customer orders. An order can have one or more payments.';

CREATE TABLE IF NOT EXISTS shipments (
    shipment_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id                  BIGINT NOT NULL,
    shipping_carrier          VARCHAR(100) NOT NULL,
    tracking_number           VARCHAR(100),
    shipment_status           VARCHAR(30) NOT NULL,
    estimated_delivery_date   DATE,

    CONSTRAINT fk_shipments_order
        FOREIGN KEY (order_id)
        REFERENCES orders (order_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT uq_shipments_tracking_number UNIQUE (tracking_number),
    CONSTRAINT ck_shipments_status
        CHECK (shipment_status IN ('Pending', 'Packed', 'Shipped', 'In Transit', 'Delivered', 'Returned', 'Cancelled'))
);

COMMENT ON TABLE shipments IS 'Shipment tracking records for customer orders. An order can have one or more shipments.';

-- ============================================================
-- 5. Indexes for foreign keys and common access paths
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_orders_customer_id
    ON orders (customer_id);

CREATE INDEX IF NOT EXISTS idx_orders_store_branch_id
    ON orders (store_branch_id);

CREATE INDEX IF NOT EXISTS idx_orders_order_date
    ON orders (order_date);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id
    ON order_items (order_id);

CREATE INDEX IF NOT EXISTS idx_order_items_product_id
    ON order_items (product_id);

CREATE INDEX IF NOT EXISTS idx_payments_order_id
    ON payments (order_id);

CREATE INDEX IF NOT EXISTS idx_payments_status
    ON payments (payment_status);

CREATE INDEX IF NOT EXISTS idx_shipments_order_id
    ON shipments (order_id);

CREATE INDEX IF NOT EXISTS idx_shipments_status
    ON shipments (shipment_status);

-- ============================================================
-- 6. Optional analytics-friendly view
-- ============================================================

CREATE OR REPLACE VIEW vw_order_sales_detail AS
SELECT
    o.order_id,
    o.order_date,
    c.customer_id,
    c.first_name,
    c.last_name,
    c.email,
    sb.store_branch_id,
    sb.store_branch_name,
    sb.store_branch_location,
    oi.order_item_id,
    p.product_id,
    p.product_name,
    p.category_id,
    oi.qty,
    oi.line_amount,
    o.total_amount
FROM orders o
JOIN customers c
    ON c.customer_id = o.customer_id
JOIN store_branch sb
    ON sb.store_branch_id = o.store_branch_id
JOIN order_items oi
    ON oi.order_id = o.order_id
JOIN products p
    ON p.product_id = oi.product_id;

COMMENT ON VIEW vw_order_sales_detail IS 'Flattened order-line view for operational reporting and validation.';
