-- Retail Sales Order Management - OLAP Star Schema
-- Target database: PostgreSQL 12+
-- Purpose: dimensional model for sales analytics.
-- Grain: one row in fact_sales represents one order item sales line.

-- To rebuild from scratch in a development database, uncomment the line below.
-- DROP SCHEMA IF EXISTS retail_dw CASCADE;

CREATE SCHEMA IF NOT EXISTS retail_dw;
SET search_path TO retail_dw;

CREATE TABLE IF NOT EXISTS dim_date (
    date_key      INTEGER PRIMARY KEY,       -- YYYYMMDD
    full_date     DATE NOT NULL UNIQUE,
    day_of_month  SMALLINT NOT NULL,
    month_number  SMALLINT NOT NULL,
    month_name    VARCHAR(20) NOT NULL,
    quarter       SMALLINT NOT NULL,
    year_number   SMALLINT NOT NULL,
    day_of_week   SMALLINT NOT NULL,
    day_name      VARCHAR(20) NOT NULL,
    is_weekend    BOOLEAN NOT NULL,

    CONSTRAINT ck_dim_date_month CHECK (month_number BETWEEN 1 AND 12),
    CONSTRAINT ck_dim_date_quarter CHECK (quarter BETWEEN 1 AND 4),
    CONSTRAINT ck_dim_date_day_of_week CHECK (day_of_week BETWEEN 1 AND 7)
);

CREATE TABLE IF NOT EXISTS dim_customers (
    customer_key          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id           BIGINT NOT NULL,
    first_name            VARCHAR(100) NOT NULL,
    last_name             VARCHAR(100) NOT NULL,
    email                 VARCHAR(255) NOT NULL,
    phone_number          VARCHAR(30),
    date_joined           DATE NOT NULL,
    effective_start_date  DATE NOT NULL DEFAULT CURRENT_DATE,
    effective_end_date    DATE,
    is_current            BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT ck_dim_customers_effective_dates
        CHECK (effective_end_date IS NULL OR effective_end_date >= effective_start_date)
);

CREATE INDEX IF NOT EXISTS idx_dim_customers_customer_id
    ON dim_customers (customer_id);

CREATE TABLE IF NOT EXISTS dim_products (
    product_key           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id            BIGINT NOT NULL,
    product_name          VARCHAR(200) NOT NULL,
    category_id           BIGINT NOT NULL,
    current_price         NUMERIC(12, 2) NOT NULL,
    stock_qty             INTEGER NOT NULL,
    effective_start_date  DATE NOT NULL DEFAULT CURRENT_DATE,
    effective_end_date    DATE,
    is_current            BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT ck_dim_products_current_price_nonnegative CHECK (current_price >= 0),
    CONSTRAINT ck_dim_products_stock_qty_nonnegative CHECK (stock_qty >= 0),
    CONSTRAINT ck_dim_products_effective_dates
        CHECK (effective_end_date IS NULL OR effective_end_date >= effective_start_date)
);

CREATE INDEX IF NOT EXISTS idx_dim_products_product_id
    ON dim_products (product_id);

CREATE TABLE IF NOT EXISTS dim_branch (
    branch_key             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_branch_id        BIGINT NOT NULL,
    store_branch_name      VARCHAR(150) NOT NULL,
    store_branch_location  VARCHAR(255) NOT NULL,
    effective_start_date   DATE NOT NULL DEFAULT CURRENT_DATE,
    effective_end_date     DATE,
    is_current             BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT ck_dim_branch_effective_dates
        CHECK (effective_end_date IS NULL OR effective_end_date >= effective_start_date)
);

CREATE INDEX IF NOT EXISTS idx_dim_branch_store_branch_id
    ON dim_branch (store_branch_id);

CREATE TABLE IF NOT EXISTS dim_payments (
    payment_key             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id              BIGINT NOT NULL,
    payment_method          VARCHAR(50) NOT NULL,
    payment_status          VARCHAR(30) NOT NULL,
    transaction_timestamp   TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_dim_payments_payment_id
    ON dim_payments (payment_id);

CREATE TABLE IF NOT EXISTS dim_shipment (
    shipment_key              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id               BIGINT NOT NULL,
    shipping_carrier          VARCHAR(100) NOT NULL,
    tracking_number           VARCHAR(100),
    shipment_status           VARCHAR(30) NOT NULL,
    estimated_delivery_date   DATE
);

CREATE INDEX IF NOT EXISTS idx_dim_shipment_shipment_id
    ON dim_shipment (shipment_id);

CREATE TABLE IF NOT EXISTS fact_sales (
    sales_key            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id             BIGINT NOT NULL,
    order_item_id        BIGINT NOT NULL,
    customer_key         BIGINT NOT NULL,
    product_key          BIGINT NOT NULL,
    branch_key           BIGINT NOT NULL,
    payment_key          BIGINT,
    shipment_key         BIGINT,
    order_date_key       INTEGER NOT NULL,
    qty                  INTEGER NOT NULL,
    line_amount          NUMERIC(12, 2) NOT NULL,
    order_total_amount   NUMERIC(12, 2) NOT NULL,
    payment_amount       NUMERIC(12, 2),
    load_timestamp       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_fact_sales_customer
        FOREIGN KEY (customer_key) REFERENCES dim_customers (customer_key),
    CONSTRAINT fk_fact_sales_product
        FOREIGN KEY (product_key) REFERENCES dim_products (product_key),
    CONSTRAINT fk_fact_sales_branch
        FOREIGN KEY (branch_key) REFERENCES dim_branch (branch_key),
    CONSTRAINT fk_fact_sales_payment
        FOREIGN KEY (payment_key) REFERENCES dim_payments (payment_key),
    CONSTRAINT fk_fact_sales_shipment
        FOREIGN KEY (shipment_key) REFERENCES dim_shipment (shipment_key),
    CONSTRAINT fk_fact_sales_order_date
        FOREIGN KEY (order_date_key) REFERENCES dim_date (date_key),

    CONSTRAINT ck_fact_sales_qty_positive CHECK (qty > 0),
    CONSTRAINT ck_fact_sales_line_amount_nonnegative CHECK (line_amount >= 0),
    CONSTRAINT ck_fact_sales_order_total_nonnegative CHECK (order_total_amount >= 0),
    CONSTRAINT ck_fact_sales_payment_amount_nonnegative CHECK (payment_amount IS NULL OR payment_amount >= 0),
    CONSTRAINT uq_fact_sales_order_item UNIQUE (order_item_id)
);

CREATE INDEX IF NOT EXISTS idx_fact_sales_customer_key
    ON fact_sales (customer_key);

CREATE INDEX IF NOT EXISTS idx_fact_sales_product_key
    ON fact_sales (product_key);

CREATE INDEX IF NOT EXISTS idx_fact_sales_branch_key
    ON fact_sales (branch_key);

CREATE INDEX IF NOT EXISTS idx_fact_sales_order_date_key
    ON fact_sales (order_date_key);

CREATE INDEX IF NOT EXISTS idx_fact_sales_payment_key
    ON fact_sales (payment_key);

CREATE INDEX IF NOT EXISTS idx_fact_sales_shipment_key
    ON fact_sales (shipment_key);

COMMENT ON TABLE fact_sales IS 'Sales fact table at one row per order item sales line. Payment and shipment keys are optional because operational orders can have multiple payment or shipment records.';
